### ISSUE TITLE
Allow to specify the project name and not get it from oc context

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift-homeroom/workshop-scripts#3]
In line https://github.com/openshift-homeroom/workshop-scripts/blob/develop/setup-environment.sh#L82 the PROJECT_NAME is get from the oc context, which means that the user executing this scripts needs to be logged into the correct project.

I would want to be able to specify the PROJECT_NAME and if not provided then it can be fetched from the user's oc context.

**Comment by GrahamDumpleton** [comment]
Could set it up to override with `--namespace` option. But, would you want the project created if it doesn't exist, or error?

**Comment by jorgemoralespou** [comment]
I would prefer an error, as this is mostly for when embedding this scripts in greater automation, so the project should exist. And of course, providing an exit code would help to manage in that automation. I don't think there's error codes defined, but only error messages to stderr.

**Comment by jorgemoralespou** [comment]
I was looking at your changes related to this issue in master and I think that you're changing completely the behavior. I was just asking that if --project is provided it uses it and if it doesn't exists it fail, otherwise, if not provided, just go with the previous behavior (for compatibility). It seems that now the latter does not happen anymore

**Comment by GrahamDumpleton** [comment]
It should work as you expect. Haven't changed existing behaviour. Have check it yet again and is released in new version now. The logic is as follows.

The `PROJECT_NAME` is set from `--project` option.

If still not set, set it from current project name.

```
if [ x"$PROJECT_NAME" == x"" ]; then
    PROJECT_NAME=`oc project --short 2>/dev/null`
fi
```

If still empty project name, error.

```
if [ x"$PROJECT_NAME" == x"" ]; then
    fail "Cannot determine name of project."
    exit 1
fi
```

Verify project exists.

```
oc get project "$PROJECT_NAME" > /dev/null 2>&1

if [ "$?" != "0" ]; then
    fail "Project $PROJECT_NAME does not exist."
    exit 1
fi
```
